const express = require('express')
const res = require('express/lib/response')
const path = require('path')
const { redirect } = require('express/lib/response')
const PORT = process.env.PORT || 5000
const bcrypt = require('bcrypt')
const flash = require('express-flash')
const session = require('express-session')

const app = express()

//allow app to find to find pages, setup view engine
app.use(express.static(path.join(__dirname, 'public')))
app.set('views', path.join(__dirname, 'views'))
app.set('view engine', 'ejs')



//passport set up
//passport setup learned from https://www.youtube.com/watch?v=-RCnNyD0L-s
//Node.js Passport Login System Tutorial by Web Dev Simplified

const users = []
const passport = require('passport')
const LocalStrategy = require('passport-local').Strategy
function startPassport(passport, getUserByName, getUserById){
  const authenticateUser = async (name,password, done) => {//name and password passed in with passport
      const user = getUserByName(name)
      if (user == null){
          return done(null, false, {message: 'No user with that username'})
      }
      try{
          if (await bcrypt.compare(password, user.password)){
              return done(null, user)
          }else{
              return done(null, false, {message: 'Incorrect password'})
          }
      }catch(e){
          return done(e)//return any errors
      }
  }
  passport.use(new LocalStrategy({ usernameField: 'name'}, authenticateUser))
  passport.serializeUser((user, done) => done(null, user.id))
  passport.deserializeUser((id, done) => {
      return done(null, getUserById(id))
  })
}

startPassport(
  passport,
  name => users.find(user => user.name === name),
  id => users.find(user => user.id === id)
)


//allow flash to work with session
app.use(express.urlencoded({extended: false}))
app.use(flash())
app.use(session({
  secret: "secret",
  resave: false,
  saveUninitialized: false
}))
app.use(passport.initialize())
app.use(passport.session())



//base homepage code
app.get('/', checkAuthentication, (req, res) => res.render('UI/ProfilePage.ejs'))

//outdated update code
app.post('/update', (req, res) => {
  var getUserQuery = req.body.code;
  console.log(getUserQuery);
  pool.query(getUserQuery, (error, result) => {
    if (error)
      res.end(error);
    res.sendStatus(200);
  })
})

//registration code
app.get('/register',  (req, res) => {
  res.render('pages/register.ejs')
})
app.post('/register', async (req, res) => {//i need to change this so it adds it to the database
  try{
    const encryptedPassword = await bcrypt.hash(req.body.password,5);
    users.push({
      id: Date.now().toString(),//autogenerated in database aka remove this
      name: req.body.name,
      password: encryptedPassword
    })
    res.redirect('/login')
  }catch{
    res.redirect('/register')
  }
  console.log(users)
})




//login code
app.get('/login2', (req, res) => {
  res.render('pages/login.ejs')
})
app.post('/login', passport.authenticate('local', {
  successRedirect: '/',
  failureRedirect: 'login',
  failureFlash: true
}))

function checkAuthentication(req, res, next){
  if (req.isAuthenticated()){
    return next();
  }
  res.redirect('/login')
}

app.get('/main', (req, res) => {
  res.render('UI/GRP4.ejs')
})
app.get('/signup', (req, res) => {
  res.render('UI/SignUp.ejs')
})
app.get('/login', (req, res) => {
  res.render('UI/LogInPage.ejs')
})
app.get('/profile', checkAuthentication, (req, res) => {
  res.render('UI/ProfilePage.ejs')
})

//listen to a port
app.listen(PORT, () => console.log(`Listening on ${ PORT }`))